### ISSUE TITLE
Chinese translated version

### ISSUE THREAD

**Issue by Heersin** [radareorg/radare2-book#305]
I have translated some parts of the radare2book and create a ![repo](https://github.com/Heersin/radare2bookCN) to maintain it (also hosted on gitbook).  It might be helpful for non-english users

**Comment by NorthShad0w** [comment]
需要合作者一起翻译么

**Comment by trufae** [comment]
i think is better to improve the original book rather than promoting translations because the source already lacks a lot of information and there's a lot of things to improve and explain better.

Thanks for your efforts anyway! Unofficial translations can be referenced from the radare2book if anyone is interested in keeping up with all that. but imho the whole book needs to be completely rewritten
